permalink: /blog/:year/:month/:day/:title.html

email: contact@rapidfirestudio.com
twitter: http://twitter.com/rapidfirestudio
facebook: http://facebook.com/rapidfirestudio

description: "RapidFire Studio makes games"
shorttitle: "RapidFire Studio"

content_imgs: /content/img
