auto: true
permalink: /blog/:year/:month/:day/:title.html

paginate_custom: 5

email: contact@rapidfirestudio.com
twitter: http://twitter.com/rapidfirestudio
facebook: http://facebook.com/rapidfirestudio