source: ./_source
plugins: ./_source/_plugins

auto: true
permalink: /blog/:year/:month/:day/:title.html

paginate: 5

email: contact@rapidfirestudio.com
twitter: http://twitter.com/rapidfirestudio
facebook: http://facebook.com/rapidfirestudio